using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JVMdotNET.Core.ClassFile
{
    [Flags]
    enum MethodAccessFlags : ushort
    {
        Public = 0x0001, // Declared public; may be accessed from outside its package.
        Private = 0x0002, // Declared private; accessible only within the defining class.
        Protected = 0x0004, // Declared protected; may be accessed within subclasses.
        Static = 0x0008, // Declared static.
        Final = 0x0010, //Declared final; must not be overridden (§5.4.5).
        Synchronized = 0x0020, // Declared synchronized; invocation is wrapped by a monitor use.
        Bridge = 0x0040, //A bridge method, generated by the compiler.
        Varargs = 0x0080, //Declared with variable number of arguments.
        Native = 0x0100, //Declared native; implemented in a language other than Java.
        Abstract = 0x0400, //Declared  abstract;  no  implementation  is provided.
        //TODO: strict floating point mode - nejspise nebude implementovan ale jeste promyslet
        Strict = 0x0800, //Declared strictfp; floating-point mode is FP-strict.
        Synthetic = 0x1000 //Declared synthetic; not present in the source code.
    }
}
